##Mode
mode: "test"  # "train", "finetune"

##Data
data:
  dataset_name: "nuscenes" # "sekitti", "KITTITRA", "KITTITRA_M", "APOLLO", "nuscenes", "WAYMO_M", "AVIA"
  voxel_size: 0.2 # Used for discretization in x,y,z when creating a sparse tensor
  time_interval: 0.05 # Temporal resolution of scans, nusc: 0.05, kitti: 0.1
  n_input: 6
  n_skip: 4
  n_output: 1  # only predict the moving status of current scan
  transform: True
  ego_mask: True

##Prediction
model:
  # 1.  train-100%nusc_epo-60_bs-16_vs-0.1_ss-10
  # 2.  train-100%sekitti_epo-60_bs-4_vs-0.1_ss-10
  # 3.  train-100%sekitti_epo-60_finetune-10%nusc_epo-10_bs-4
  # 3.1 mask_train-100%sekitti_epo-60_finetune-10%nusc_epo-60_bs-16_vs-0.1_ss-10
  # 4.  train-10%nusc_epo-10_bs-4_vs-0.1_ss-10
  # 5.  train-100%sekitti_epo-60_finetune-5%nusc_epo-5_bs-4
  # 6.  train-5%nusc_epo-5_bs-4_vs-0.1_ss-10

  # 0.  mask_train-100%sekitti_epo-60_finetune-10%nusc_epo-60_bs-4_vs-0.1_ss-10
  # 1.  train-100%sekitti_epo-60_finetune-10%nusc_epo-60_bs-16_vs-0.1_ss-10
  model_dataset: "100%nuscenes"
  model_name: "vs-0.2_t-1.3_bs-4"
  model_version: "version_0"
  num_devices: 1
  batch_size: 4
  num_workers: 1

# Dataset Config
dataset:
  nuscenes: # ours label
    root: "/home/user/Datasets/nuScenes"  # /root/autodl-tmp/Datasets/nuScenes /home/user/Datasets/nuScenes
    version: "v1.0-trainval" # "v1.0-mini"
  SEKITTI:
    PATH: "/home/user/Datasets/SeKITTI/sequences" # labeled by PRPonn, seq 00-21
    SEMANTIC_CONFIG_FILE: "./config/semantic-kitti-mos.yaml"
    POSES: "poses.txt" # Name of the pose file provided in each sequence folder (OPTIONS: FastLIO2 and poses provided by dataset)
    LIDAR_NAME: "velodyne"
    DELTA_T: 0.1 # Time between scans in the dataset (0.1s for KITTI)
    TRAIN: [0, 1, 2, 3, 4, 5, 6, 7, 9, 10]
    VAL: [8]
    TEST: [8]
  KITTITRA:
    PATH: "./data/KITTITra/sequences" # labeled by PRPonn, seq 19
    LIDAR_NAME: "velodyne"
  KITTITRA_M:
    PATH: "./data/KITTITra_M/sequences" # labeled by MaRS, seq 00, 01-20
    LIDAR_NAME: "velodyne"
  APOLLO: # labeled by PRPonn, seq 00-04
    PATH: "./data/Apollo/sequences"
    LIDAR_NAME: "velodyne"
  WAYMO_M: # labeled by MaRS, seq ?00-43 (NOT ORG IDX)
    PATH: "./data/Waymo_M/sequences"
    LIDAR_NAME: "lidar"