##Data
data:
  pc_range: [-70.0, -70.0, -4.5, 70.0, 70.0, 4.5]  # valid point cloud range [-x, -y, -z, x, y, z]
  voxel_size: 0.2  # voxel size
  n_input: 6  # number of input point cloud scan
  n_output: 6  # number of output point cloud scan (for pretraining only)
  ego_mask: True # mask the points of ego-vehicle, 4docc pretraining default=True
#  x_flip: True  # flip the x-axis in Singapore (left hand drive)
  n_mos_class: 3  # number of predicted mos class (0-unknown, 1-static, 2-moving)
#  transform: True # If true, the points are pose-aligned before feeding to the model
#  shuffle: True  # shuffle the dataset
  eval_outside_grid: False
  eval_within_grid: True

##Testing
model:
  expt_dir: "models/nusc/3s_forecasting_vs-0.2"  # experiment directory
  expt_name: "nusc_3s_mos"
  test_epoch: 14  # last fine-tuning epoch
  loss_type: "nll"
  batch_size: 2
  num_workers: 24
  num_devices: 1 # could be integer of how many cuda devices to use, or a list that specify which devices to use [0, 1, 2, 3]
  # ACC_BATCHES: 1 # accumulate gradients over k batches before stepping into the optimizer
  # AUGMENTATION: True

# Dataset Config
dataset:
  name: "nuscenes"  # "kitti", "argo"
  nuscenes:
    root: "/home/user/Datasets/nuScenes"
    version: "v1.0-trainval"
    train_split: "train"
    val_split: "val"
    test_split: "val"
  kitti:
    root: "/home/user/Datasets/KITTI"
    config: "configs/semantic-kitti.yaml"
  argo:
    root: "/home/user/Datasets/ArgoVerse2/LiDAR/"
    subsample: 1
