##Data
data:
  dataset_name: "nuscenes"
  pc_range: [-70.0, -70.0, -4.5, 70.0, 70.0, 4.5]  # valid point cloud range
  input_within_pc_range: True
  voxel_size: 0.2  # voxel size
  n_input: 6  # number of input point cloud scan
  n_output: 6  # number of output point cloud scan (for pretraining only)
  ego_mask: True # mask the pointgit as of ego-vehicle, 4docc pretraining default=True
  flip: True  # flip the x-axis in Singapore (left hand drive)
#  transform: True # If true, the points are pose-aligned before feeding to the model
  shuffle: False  # shuffle the dataset

##Testing
model:
  model_name: "pretrain_vs-0.2_t-3.0_bs-1_epo-60"  # model directory
  model_version: "version_0"
  test_epoch: 9
  loss_type: "l1"  # "l1", "l2", "absrel" for pre-training only
  batch_size: 1
  num_workers: 8
  num_devices: 1 # could be integer of how many cuda devices to use, or a list that specify which devices to use [0, 1, 2, 3]
  metrics: ["chamfer_dist"]
  plot_metrics: True
  write_pcd: False
  assume_const_velo: True
  eval_within_grid: False
  eval_outside_grid: False

# Dataset Config
dataset:
  nuscenes:
#    root: "/root/autodl-tmp/Datasets/nuScenes"
    root: "/home/user/Datasets/nuScenes"
    version: "v1.0-trainval"
  kitti:
    root: "/home/user/Datasets/KITTI"
    config: "configs/semantic-kitti.yaml"
  argo:
    root: "/home/user/Datasets/ArgoVerse2/LiDAR/"
