# Pretraining params
moco:  # mutual observation pretraining
  # dataset related
  dataset_name: "sekitti" # "sekitti", "KITTITRA", "KITTITRA_M", "APOLLO", "nuscenes", "WAYMO_M", "AVIA"
  downsample_level: "sequence" # "sequence", "sample", "none"
  downsample_pct: 100 # use 10% of training dataset to train the model
  shuffle: True # not used, random sampler default shuffle?
  augmentation: True

  # pre-processing
  split_size: 4
  uni_ds: 6
  max_range: 100 # sqrt(70^2 + 70^2 + 4.5^2)
  dvg_ang: 0.0020 # beam divergence angle (Velodyne HDL-32E: 0.003 (horizontal), 0.0012 (vertical))
  occ_thrd: 0.105361  # -ln(0.9)
  unk_thrd: 2.302585 # -ln(0.1)
  n_sd_per_sample: 1

  # data processing related
  n_input: 6
  n_skip: 4
  scene_bbox: [-70.0, -70.0, -4.5, 70.0, 70.0, 4.5] # valid point cloud range
  quant_size: 0.1 # used for discretization in x,y,z when creating a sparse tensor
  time_interval: 0.1 # sample data time interval, nusc: 0.05, kitti: 0.1; sample time interval: nusc: 0.5
  pos_dim: 4 # x, y, z, t
  feat_dim: 128 # feature dimension of each point
  transform: True # if true, the points are pose-aligned before feeding to the model
  ego_mask: True
  outside_scene_mask: True
  outside_scene_mask_z: False
  outside_scene_mask_ub: True # upper bound, if true, x <= x_max, else x < x_max

  # training related
  num_epoch: 50
  batch_size: 8
  acc_batches: 1 # accumulate gradients over k batches before stepping into the optimizer
  num_cls: 3 # 0-unknown, 1-free, 2-occ
  # mutual observation
  train_bg_mo_samples: True # if True, only use background mutual observation samples for pre-training
  mo_samples_free_pct: 100 # 500% free mo samples, compared to occ samples
  mo_samples_unk_pct: 100 # 500% unknown mo samples, compared to occ samples
  # current observation
  train_co_samples: True
  num_co_rays_free: 25
  num_co_rays_occ: 5 # 20000 * 110 = 2,200,000 co samples for a scan
  # learning scheduler
  lr_start: 0.000005  # refer to UnO [8e-5]
  lr_max: 0.00005  # refer to UnO [8e-4]
  lr_min: 0  # refer to UnO
  weight_decay: 0.0001  # refer to UnO [1e-4]

  # device related
  num_workers: 16
  num_devices: 2 # int: number of cuda devices to use; list: specify which devices to use [0, 1, 2, 3]


# Background samples test
moco_test:
  model_dir: './logs/ours/mop_bg_100%unk_shuffle/100%nuscenes/vs-0.1_t-3.0_bs-16/version_0'
  test_epoch: [49, 39, 29, 19, 09]
  test_dataset: 'nuscenes'
  num_devices: 1
  save_pred_labels: False